version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    ignore:
      # the releases are inconsistent - the latest jaxb-api does not work with the latest jaxb-runtime 
      - dependency-name: "javax.xml.bind:jaxb-api"
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "automatic-merge"
